In [2]:
from numpy import *
import numpy as np
import pandas as pd
from IPython.display import display
from IPython.display import Image
import seaborn as sns
sns.set(style="white", color_codes=True)


from sklearn.neighbors import KNeighborsClassifier
# from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline



In [1]:
# data=pd.read_csv('Downloads/iris.csv')
# #data.head(1)
# data.drop('Id',axis=1,inplace=True)
# data['Species']=np.where(data['Species']=='Iris-setosa',0,np.where(data['Species']=='Iris-versicolor',1,2))
# #data.head(1)
# #print(data.info())
# X=data.values[:,:4]
# #print X
# y=data.values[:,4]
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# print X_test
# #data.shape
# # data.head(1)
# #data['Species']=np.where(data['Species']=='Iris-setosa',0,np.where(data['Species']=='Iris-versicolor',1,2))
# # for i in range(0,2999):
# #     if (data['Species']=='Iris-setosa'):
# #         data['Species']=0
        
# #data['Species'] = data['Species'].map(lambda Iris-setosa:0)#,1,2])
# #y=data.values[:,4]
# #print(type(y))



In [4]:
##ON Data-Standardization(-ve and +ve balanced values-Uniform distribution-zero mean-less sensitive to outliers)
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)#fit nd then transform
X_test_std = stdsc.transform(X_test)#only transform
#print(X_test_std)

NameError: name 'X_train' is not defined

In [4]:
##ON Data-Normalization[0-1]
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)
print(X_test_norm)

[[ 0.41666667  0.33333333  0.68965517  0.95833333]
 [ 0.47222222  0.08333333  0.5         0.375     ]
 [ 0.33333333  0.91666667  0.05172414  0.04166667]
 [ 0.83333333  0.375       0.89655172  0.70833333]
 [ 0.19444444  0.58333333  0.06896552  0.04166667]
 [ 0.55555556  0.54166667  0.84482759  1.        ]
 [ 0.19444444  0.625       0.03448276  0.08333333]
 [ 0.66666667  0.45833333  0.62068966  0.58333333]
 [ 0.69444444  0.33333333  0.63793103  0.54166667]
 [ 0.5         0.33333333  0.5         0.5       ]
 [ 0.5         0.25        0.77586207  0.54166667]
 [ 0.58333333  0.5         0.5862069   0.58333333]
 [ 0.5         0.33333333  0.62068966  0.45833333]
 [ 0.61111111  0.33333333  0.60344828  0.58333333]
 [ 0.5         0.375       0.62068966  0.54166667]
 [ 0.16666667  0.45833333  0.06896552  0.        ]
 [ 0.47222222  0.375       0.5862069   0.58333333]
 [ 0.33333333  0.25        0.56896552  0.45833333]
 [ 0.13888889  0.41666667  0.05172414  0.08333333]
 [ 0.30555556  0.79166667  0.03

In [31]:
##ON Model-Regularization-L1 TO AVOID OVERFITTING when high dimensional data-overfitting-L1 gives Sparse solution i.e.remove irrelevant features
from sklearn.linear_model import LogisticRegression

# WITHOUT REGULARIZATION 
lr1=LogisticRegression(C=1000)
lr1.fit(X_train_std, y_train)
print('Training accuracy:', lr1.score(X_train_std, y_train))
print('Test accuracy:', lr1.score(X_test_std, y_test))

##AFTER REGULARIZATION
lr=LogisticRegression(penalty='l2',C=10)
lr.fit(X_train_std, y_train)
print('Training accuracy:', lr.score(X_train_std, y_train))
print('Test accuracy:', lr.score(X_test_std, y_test))

##REGULARIZATION ON NON STANDARDIZED DATA
lr2=LogisticRegression(penalty='l2',C=10)
lr2.fit(X_train, y_train)
print('Training accuracy:', lr2.score(X_train, y_train))
print('Test accuracy:', lr2.score(X_test, y_test))

##SIMPLE LOGISTIC REGRESSION(BEST RESULTS)
lr3=LogisticRegression()
lr3.fit(X_train, y_train)
print('Training accuracy:', lr3.score(X_train, y_train))
print('Test accuracy:', lr3.score(X_test, y_test))

('Training accuracy:', 0.99047619047619051)
('Test accuracy:', 0.97777777777777775)
('Training accuracy:', 0.94285714285714284)
('Test accuracy:', 0.9555555555555556)
('Training accuracy:', 0.99047619047619051)
('Test accuracy:', 0.93333333333333335)
('Training accuracy:', 0.94285714285714284)
('Test accuracy:', 0.88888888888888884)


In [26]:
##SVM IMPLEMENTATION #Linear kernel better than rbf here
##LOOK BOTH GAMMA AND C
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=0, gamma=0.10, C=10)
svm.fit(X_train_norm, y_train)
print('Training accuracy:', svm.score(X_train_norm, y_train))
print('Test accuracy:', svm.score(X_test_norm, y_test))


('Training accuracy:', 0.97142857142857142)
('Test accuracy:', 0.97777777777777775)


In [30]:
##Decision Tree 
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='entropy',max_depth=3, random_state=0)
tree.fit(X_train_std, y_train)
print('Training accuracy:', tree.score(X_train_std, y_train))
print('Test accuracy:', tree.score(X_test_std, y_test))


('Training accuracy:', 0.98095238095238091)
('Test accuracy:', 0.97777777777777775)


In [33]:
## RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(criterion='entropy',
n_estimators=10,
random_state=1,
n_jobs=2)
forest.fit(X_train, y_train)
print('Training accuracy:', forest.score(X_train, y_train))
print('Test accuracy:', forest.score(X_test, y_test))


('Training accuracy:', 1.0)
('Test accuracy:', 0.97777777777777775)


In [37]:
##KMEANS CLASSIFIER## NORMALISATION AND STANDARDIZATION BOTH DEGRADE RESULTS
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2,
metric='minkowski')
knn.fit(X_train, y_train)
print('Training accuracy:', forest.score(X_train, y_train))
print('Test accuracy:', forest.score(X_test, y_test))

('Training accuracy:', 1.0)
('Test accuracy:', 0.97777777777777775)


In [6]:
##FEATURE EXTRACTION-PCA AND PIPELINE(SERIES OF STEPS TAKE PLACE TOGETHER & THEN RESULT ACHIEVED) CONCEPT
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe_lr = Pipeline([('scl', StandardScaler()),('pca', PCA(n_components=3)),
('clf', LogisticRegression(penalty='l1',random_state=1))])
pipe_lr.fit(X_train, y_train)
pipe_lr.score(X_test, y_test)
##Max accuracy achieved of all the cases on using penalty parameter as well

0.91111111111111109

In [7]:
##FEATURE SELECTION USING RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=10000,random_state=0,n_jobs=-1)
forest.fit(X_train, y_train)
importances = forest.feature_importances_
# forest.fit(X_train_std, y_train)
# importances2 = forest.feature_importances_
##BOTH IMPORTANCES RESULT SAME
print(importances)#,importances2)*111*1*5*4#

[ 0.10737218  0.025838    0.45810717  0.40868265]


In [8]:
# #relations
# #data.info()
#EEspecies_seLcat1 = data[data['Species']==0]['PetalLengthCm'].value_counts()
#EE species_seLcat2 = data[data['Species']==1]['SepalWidthCm'].value_counts()
# EE species_seLcat3 = data[data['Species']==2]['SepalWidthCm'].value_counts()
#print(species_seLcat1)
# df = pd.DataFrame([species_seLcat3])#,species_seLcat2,species_seLcat3])
# # df = pd.DataFrame([species_seLcat1,species_seLcat2,species_seLcat3])
# # df.index = ['1st category','2nd category','3rd category']
# df.plot(kind='bar', figsize=(15,8))
#EEdata.plot(kind="scatter", x="PetalLengthCm", y="PetalWidthCm")
#EEg = sns.factorplot("PetalLengthCm","PetalWidthCm", "Species",data=data,kind='swarm',size=10)
#equivalent to g but factorplot does not require to specify sequence
# sns.FacetGrid(data, hue="Species", size=5) \
#    .map(plt.scatter, "SepalLengthCm", "SepalWidthCm") \
#    .add_legend()
#EEsns.boxplot(x="Species", y="SepalLengthCm", data=data)
#EESaving the resulting axes as ax each time causes the resulting plot to be shown
# on top of the previous axes
#EEsns.boxplot(x="Species", y="PetalLengthCm", data=data)
#EEax=sns.stripplot(x="Species", y="PetalLengthCm", data=data, jitter=True, edgecolor="gray",size=10)
#EEsns.violinplot(x="Species", y="PetalLengthCm", data=data, size=6)

In [9]:
#EEsns.violinplot(x="Species", y="PetalLengthCm", data=data, size=6)
#EE y axis in below gives no of times a particular val occcurs
#EEsns.FacetGrid(data, hue="Species", size=6) \
#   .map(sns.kdeplot, "PetalLengthCm") \
#   .add_legend()
#EEsns.pairplot( hue="Species",data=data)
#EEesns.pairplot(data=data, hue="Species", size=3, diag_kind='kde')
# knn=KNeighborsClassifier(n_neighbors=3)
# scores = cross_val_score(knn,X,y,cv=10,scoring='accuracy')
# # scores=cross_val_score(knn,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(y)
#EEX_train_std = sc.transform(X_train)
#EEX_test_std =sc.transform(X_test)
yyy=sc.transform(y_train)
print yyy


## NOTICE this way  print('There are {} samples in the training set and {} samples in the test set'.format(
##X_train.shape[0], X_test.shape[0]))


[ 0.          1.22474487  1.22474487  1.22474487  1.22474487  0.
  1.22474487  0.          0.          1.22474487  1.22474487  1.22474487
  1.22474487  0.          1.22474487  0.         -1.22474487  1.22474487
  0.          0.          0.          0.          1.22474487 -1.22474487
 -1.22474487  1.22474487  0.         -1.22474487 -1.22474487  0.
 -1.22474487  1.22474487  0.         -1.22474487  0.          1.22474487
  0.         -1.22474487  1.22474487  1.22474487  1.22474487  1.22474487
 -1.22474487 -1.22474487  1.22474487  1.22474487 -1.22474487  1.22474487
 -1.22474487  1.22474487  1.22474487 -1.22474487 -1.22474487  1.22474487
 -1.22474487 -1.22474487 -1.22474487  0.          1.22474487  1.22474487
 -1.22474487 -1.22474487 -1.22474487  0.          0.         -1.22474487
 -1.22474487  0.         -1.22474487  1.22474487  0.          1.22474487
  0.         -1.22474487  1.22474487 -1.22474487  1.22474487 -1.22474487
 -1.22474487  1.22474487 -1.22474487  1.22474487  0.          0.   

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
